//~ Revision: 97, Copyright (C) 2014-2017: Willem Vree
//~ This program is free software; you can redistribute it and/or modify it under the terms of the
//~ Lesser GNU General Public License as published by the Free Software Foundation;
//~ This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
//~ without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//~ See the Lesser GNU General Public License for more details. <http://www.gnu.org/licenses/lgpl.html>.
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(m,y,p){if(p.get||p.set)throw new TypeError("ES3 does not support getters and setters.");m!=Array.prototype&&m!=Object.prototype&&(m[y]=p.value)};$jscomp.getGlobal=function(m){return"undefined"!=typeof window&&window===m?m:"undefined"!=typeof global&&null!=global?global:m};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(m){return $jscomp.SYMBOL_PREFIX+(m||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var m=$jscomp.global.Symbol.iterator;m||(m=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[m]&&$jscomp.defineProperty(Array.prototype,m,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(m){var y=0;return $jscomp.iteratorPrototype(function(){return y<m.length?{done:!1,value:m[y++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(m){$jscomp.initSymbolIterator();m={next:m};m[$jscomp.global.Symbol.iterator]=function(){return this};return m};$jscomp.iteratorFromArray=function(m,y){$jscomp.initSymbolIterator();m instanceof String&&(m+="");var p=0,t={next:function(){if(p<m.length){var u=p++;return{value:y(u,m[u]),done:!1}}t.next=function(){return{done:!0,value:void 0}};return t.next()}};t[Symbol.iterator]=function(){return t};return t};
$jscomp.polyfill=function(m,y,p,t){if(y){p=$jscomp.global;m=m.split(".");for(t=0;t<m.length-1;t++){var u=m[t];u in p||(p[u]={});p=p[u]}m=m[m.length-1];t=p[m];y=y(t);y!=t&&null!=y&&$jscomp.defineProperty(p,m,{configurable:!0,writable:!0,value:y})}};$jscomp.polyfill("Array.prototype.keys",function(m){return m?m:function(){return $jscomp.iteratorFromArray(this,function(m){return m})}},"es6-impl","es3");
$jscomp.findInternal=function(m,y,p){m instanceof String&&(m=String(m));for(var t=m.length,u=0;u<t;u++){var A=m[u];if(y.call(p,A,u,m))return{i:u,v:A}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(m){return m?m:function(m,p){return $jscomp.findInternal(this,m,p).v}},"es6-impl","es3");var xml2abc_VERSION=97,vertaal;
(function(){function m(a,b){return Array(a+1).join(b)}function y(a,b){for(var c=[];a;)c.push(b),--a;return c}function p(a,b){for(var c=0,d={};c<a.length;++c)d[a[c]]=b[c];return d}function t(a,b){var c=a.split(/%[ds]/);c.length>b.length&&b.push("");return b.map(function(a,b){return c[b]+a}).join("")}function u(a,b){v.info(t(a,b))}function A(a,b){return-1!==a.indexOf(b,a.length-b.length)}function F(a){return Object.keys(a).map(function(a){return parseInt(a)})}function J(a,b){var c=[],d;if(Array.isArray(a))for(d=
0;d<a.length;++d)d in a&&c.push([d,a[d]]);else for(d in a)c.push([d,a[d]]);c.sort(b?function(a,b){return a[0]-b[0]}:function(a,b){return a[1]-b[1]||b[0]-a[0]});return c}function K(a){this.reset();this.ixp=a;this.divs=this.mdur=this.ixm=0}function B(a,b){this.tijd=0;this.dur=a;this.fact=null;this.tup=[""];this.tupabc="";this.grace=this.beam=0;this.before=[];this.after="";this.ns=b?[b]:[];this.lyrs={};this.pos=0;this.tab=null;this.ntdec=""}function C(a){this.tijd=0;this.str=a;this.pos=0}function D(){}
function z(a){this.maxtime=this.tijd=0;this.gMaten=[];this.gLyrics=[];this.vnums={};this.cnt=new D;this.vceCnt=1;this.lastnote=null;this.bpl=a.b;this.cpl=a.n;this.repbra=0;this.nvlt=a.v}function E(a,b,c,d){this.fnmext=a;this.outlist=[];this.infolist=[];this.title="T:Title";this.key="none";this.clefs={};this.mtr="none";this.tempo=0;this.tempo_units=[1,4];this.pad=b;this.X=c+1;this.denL=d.d;this.volpan=d.m;this.cmpL=[];this.scale="";this.tstep=d.t;this.stemless=0;this.rightmargin=this.leftmargin=this.pagewidth=
"";this.shiftStem=d.s;4==d.p.length&&(this.scale=""!=d.p[0]?parseFloat(d.p[0]):"",this.pagewidth=""!=d.p[1]?parseFloat(d.p[1]):"",this.leftmargin=""!=d.p[2]?parseFloat(d.p[2]):"",this.rightmargin=""!=d.p[3]?parseFloat(d.p[3]):"")}function T(a,b){if(!a.join(""))return["",0];for(var c=[],d=0;d<a.length;++d){var f=a[d];""==f?f=b?"_":"*":A(f,"_")&&!A(f,"\\_")?(f=f.replace("_",""),b=1):b=0;c.push(f)}return[c.join(" "),b]}function G(a,b){for(var c=a,d=b,f;b;)f=a%b,a=b,b=f;return[c/a,d/a]}function L(a,b,
c){if(0==a.dur)return"";var d;d=G(c*a.dur,4*b);b=d[0];c=d[1];a.fact&&(d=a.fact[0],a=a.fact[1],d=G(b*d,c*a),b=d[0],c=d[1]);64<c&&(a=b/c,d=Math.floor(a),a-d<.1*a&&(b=d,c=1),d=G(Math.round(64*b/c)||1,64),u("denominator too small: %d/%d rounded to %d/%d",[b,c,d[0],d[1]]),b=d[0],c=d[1]);return 1==b?1==c?"":2==c?"/":"/"+c:1==c?""+b:b+"/"+c}function M(a){var b=a.match(/([_^]*)([A-Ga-g])([',]*)/);if(!b)return-1;a=b[1];var c=b[2],b=b[3],d;d=c.toUpperCase();c=60+[0,2,4,5,7,9,11]["CDEFGAB".indexOf(d)]+(d!=c?
12:0);a&&(c+=("^"==a[0]?1:-1)*a.length);b&&(c+=("'"==b[0]?12:-12)*b.length);return c}function U(a,b,c,d){var f;f=0;0<=c.indexOf("stafflines=1")&&(f+=4);!d&&0<=c.indexOf("bass")&&(f+=12);f&&(c="CDEFGAB".split(""),f=c.indexOf(a)+f,a=c[f%7],b+=Math.floor(f/7));4<b&&(a=a.toLowerCase());5<b&&(a+=m(b-5,"'"));4>b&&(a+=m(4-b,","));return a}function V(a,b){var c,d;d={maj:8,ion:8,m:11,min:11,aeo:11,mix:9,dor:10,phr:12,lyd:7,loc:13,non:8};b=b.slice(0,3).toLowerCase();d="Fb Cb Gb Db Ab Eb Bb F C G D A E B F# C# G# D# A# E# B#".split(" ")[d[b]+
a]+(8!=d[b]?b:"");c="FCGDAEB".split("");c=0<=a?p(c.slice(0,a),y(a,1)):p(c.slice(a),y(-a,-1));return[d,c]}function N(a,b,c){var d=0,f,e,g=b[a];e=g.tup.indexOf("start");-1<e&&g.tup.splice(e,1);var h=a;for(c=[g.fact[0]/c[0],g.fact[1]/c[1]];a<b.length;){g=b[a];if(!(g instanceof C||g.grace)){-1<g.tup.indexOf("start")?(e=N(a,b,c),a=e[0],e=e[1],d+=e):g.fact&&(d+=1);e=g.tup.indexOf("stop");if(-1<e){g.tup.splice(e,1);break}if(!g.fact){a=f;break}f=a}a+=1}f=[c[0],c[1],d];f="3,2,3"==f.toString()?"(3":t("(%d:%d:%d",
f);b[h].tupabc=f+b[h].tupabc;return[a,d]}function W(a){a=a.filter(function(a){return a instanceof B});for(var b=0;b<a.length-1;){var c=a[b],d=a[b+1];!c.fact&&!d.fact&&0<c.dur&&d.beam&&(3*c.dur==d.dur?(d.dur=2*d.dur/3,c.dur*=2,c.after="<"+c.after,b+=1):3*d.dur==c.dur&&(c.dur=2*c.dur/3,d.dur*=2,c.after=">"+c.after,b+=1));b+=1}}function X(a,b,c,d,f){for(d=0;d<a.length;)c=a[d],c instanceof B&&c.fact&&!c.grace&&(c=N(d,a,[1,1]),d=c[0]),d+=1;d=[];for(var e,g=0;g<a.length;++g){c=a[g];if(c instanceof B){var h=
L(c,b,f),k=1<c.ns.length;e=c.ns.filter(function(a){return A(a,"-")});e=e.map(function(a){return a.slice(0,-1)});var l="";k&&e.length==c.ns.length&&(c.ns=e,l="-");e=c.tupabc+c.before.join("");k&&(e+="[");e+=c.ns.join("");k&&(e+="]"+l);A(e,"-")&&(e=e.slice(0,-1),l="-");e+=h+l;e+=c.after;c=c.beam}else c.str instanceof Array&&(c.str=c.str[0]),e=c.str,c=1;c?d.push(e):d.push(" "+e)}for(d=d.join("");0<=d.indexOf("!ped!!ped!");)d=d.replace(/!ped!!ped!/g,"!ped!");for(;0<=d.indexOf("!ped-up!!ped-up!");)d=d.replace(/!ped-up!!ped-up!/g,
"!ped-up!");for(;0<=d.indexOf("!8va(!!8va)!");)d=d.replace(/!8va\(!!8va\)!/g,"");return d}function Y(a,b){a.map(function(a,b){a.pos=b});a.sort(function(a,b){return a.tijd-b.tijd||a.pos-b.pos});for(var c=0,d=[],f=0;f<a.length;++f){var e=a[f];e.tijd>c&&d.push(new B(e.tijd-c,"x"));if(e instanceof C)e.tijd<c&&(e.tijd=c),d.push(e),c=e.tijd;else{if(e.tijd<c){if("z"==e.ns[0])continue;var g=d[d.length-1];if(g.tijd<=e.tijd)if("z"==g.ns[0])g.dur=e.tijd-g.tijd,0==g.dur&&d.pop(),u("overlap in part %d, measure %d: rest shortened",
[b.ixp+1,b.ixm+1]);else{g.ns=g.ns.concat(e.ns);u("overlap in part %d, measure %d: added chord",[b.ixp+1,b.ixm+1]);e.dur=e.tijd+e.dur-c;if(0>=e.dur)continue;e.tijd=c}else{u("overlapping notes in one voice! part %d, measure %d, note %s discarded",[b.ixp+1,b.ixm+1,e instanceof B?e.ns:e.str]);continue}}d.push(e);c=e.tijd+e.dur}}0==c&&u("empty measure in part %d, measure %d, it should contain at least a rest to advance the time!",[b.ixp+1,b.ixm+1]);return d}function Z(a){function b(a){a=t('<part-group number="%d" type="%s"></part-group>',
[a,"stop"]);a=(new window.DOMParser).parseFromString(a,"text/xml").firstChild;return $(a)}var c,d,f,e,g,h,k;c=[];d=[];h=a.children();for(g=0;g<h.length;g++)a=$(h[g]),"part-group"==a[0].nodeName?(f=a.attr("number"),e=a.attr("type"),k=d.indexOf(f),"start"==e?-1<k?(c.push(b(f)),c.push(a)):(c.push(a),d.push(f)):-1<k&&(d.splice(k,1),c.push(a))):c.push(a);for(g=d.length-1;0<=g;--g)f=d[g],c.push(b(f));return c}function H(a,b,c){var d,f,e,g;if(0==a.length)return[[],[]];d=a.shift();if("part-group"==d[0].nodeName){f=
d.attr("number");e=d.attr("type");if("start"==e){e=[];for(g in{"group-symbol":0,"group-barline":0,"group-name":0,"group-abbreviation":0})e.push(d.find(g).text()||"");b[f]=e;c.push(f);g=H(a,b,c);a=g[0];d=g[1];g=H(d,b,c);b=g[0];c=g[1];return[[a].concat(b),c]}c=c.pop();a.length&&"stop"==a[0].attr("type")&&f!=c&&(g=b[c],b[c]=b[f],b[f]=g);b=b[f];return[[b],a]}g=H(a,b,c);b=g[0];a=g[1];return[[["name_tuple",d.find("part-name").text()||"",d.find("part-abbreviation").text()||""]].concat(b),a]}function O(a){var b,
c,d,f;if(0==a.length)return[];b=[];for(d=0;d<a.length;++d){c=a[d];if(1==c.length)b.push(""+c[0]);else{b.push("(");for(f=0;f<c.length;++f)b.push(""+c[f]);b.push(")")}b.push("|")}b.splice(-1,1);1<a.length&&(b=["{"].concat(b).concat(["}"]));return b}function P(a,b,c,d,f,e){if("name_tuple"==a[0])d=d.shift(),b[0]&&(a[1]=b[0]+":"+a[1],a[2]=b[1]+":"+a[2]),f.push(a),e.push.apply(e,O(d));else if(2==a.length)d=d.shift(),c=["name_tuple","",""],c[1]=a[0][1]+":"+a[1][2],c[2]=a[0][2]+":"+a[1][3],f.push(c),e.push.apply(e,
O(d));else{var g,h,k;k=a[a.length-1];b=k[0];g=k[1];h=k[2];k=k[3];g="yes"==g||c;e.push("brace"==b?"{":"[");for(c=0;c<a.length-1;++c)P(a[c],[h,k],g,d,f,e),g&&e.push("|");g&&e.splice(-1,1);e.push("brace"==b?"}":"]")}}function aa(a){for(var b="",c=a.children(),d=0;d<c.length;++d){var f=c[d];switch(f.nodeName){case "elision":b+="~";break;case "text":b+=$(f).text().replace(/_/g,"\\_").replace(/-/g,"\\-").replace(/ /g,"~")}}if(!b)return b;c=a.find("syllabic").text();if("begin"==c||"middle"==c)b+="-";a.find("extend").length&&
(b+="_");return b}function ba(a){var b={diamond:1,triangle:1,square:1,normal:1},c=ca,d,f,e,g="default",h={"default":[]};a=a.split("\n");for(d=0;d<a.length;++d)if(f=a[d],0<=f.indexOf("I:percmap")&&(f=f.split(" ").map(function(a){return a.trim()}),e=f[4],e in b&&(e=e+"+,"+e),f="%%map perc"+g+" "+f[1]+" print="+f[2]+" midi="+f[3]+" heads="+e,h[g].push(f)),0<=f.indexOf("V:")&&(e=f.match(/V:\s*(\S+)/)))g=e[1],g in h||(h[g]=[]);b=Object.keys(h).sort();for(d=0;d<b.length;++d)c=c.concat(h[b[d]]);for(d=0;d<
a.length;++d)f=a[d],0<=f.indexOf("I:percmap")||(0<=f.indexOf("V:")||0<=f.indexOf("K:")?((e=f.match(/V:\s*(\S+)/))&&(g=e[1]),0==h[g].length&&(g="default"),c.push(f),0<=f.indexOf("perc")&&-1==f.indexOf("map=")&&(f+=" map=perc"),0<=f.indexOf("map=perc")&&0<h[g].length&&c.push("%%voicemap perc"+g),0<=f.indexOf("map=off")&&c.push("%%voicemap")):c.push(f));return c.join("\n")}function I(a,b){var c=a;4<b&&(c=a.toLowerCase());5<b&&(c+=m(b-5,"'"));4>b&&(c+=m(4-b,","));return c}function x(a){this.slurBuf={};
this.dirStk={};this.ingrace=0;this.msc=new z(a);this.unfold=a.u;this.ctf=a.c;this.gStfMap=[];this.midiMap=[];this.drumInst={};this.drumNotes={};this.instMid=[];this.midDflt=[-1,-1,-1,-91];this.msralts={};this.curalts={};this.stfMap={};this.clefMap={};this.curClef={};this.clefOct={};this.curStf={};this.nolbrk=a.x;this.doPageFmt=1==a.p.length;this.tstep=a.t;this.dirtov1=a.v1;this.ped=!a.noped;this.pedVce=null;this.repeat_str={};this.tabVceMap={};this.koppen={};this.note_alts=["=C ^C =D ^D =E =F ^F =G ^G =A ^A =B".split(" "),
"^B _D ^^C _E _F ^E _G ^^F _A ^^G _B _C".split(" "),"__D ^^B __E __F ^^D __G ^^E __A _/A __B __C ^^A".split(" ")];this.step_map={C:0,D:2,E:4,F:5,G:7,A:9,B:11}}var da=Math.pow(2,53),Q={"ornaments>trill-mark":"T","ornaments>mordent":"M","ornaments>inverted-mordent":"P","ornaments>turn":"!turn!","ornaments>inverted-turn":"!invertedturn!","technical>up-bow":"u","technical>down-bow":"v","technical>harmonic":"!open!","technical>open-string":"!open!","technical>stopped":"!plus!","technical>snap-pizzicato":"!snap!",
"technical>thumb-position":"!thumb!","articulations>accent":"!>!","articulations>strong-accent":"!^!","articulations>staccato":".","articulations>staccatissimo":"!wedge!","articulations>scoop":"!slide!",fermata:"!fermata!",arpeggiate:"!arpeggio!","articulations>tenuto":"!tenuto!","articulations>spiccato":"!wedge!","articulations>breath-mark":"!breath!","articulations>detached-legato":"!tenuto!."},R={p:"!p!",pp:"!pp!",ppp:"!ppp!",pppp:"!pppp!",f:"!f!",ff:"!ff!",fff:"!fff!",ffff:"!ffff!",mp:"!mp!",
mf:"!mf!",sfz:"!sfz!"},ca='%%beginsvg\n<defs>,<text id="x" x="-3" y="0">&#xe263;</text>,<text id="x-" x="-3" y="0">&#xe263;</text>,<text id="x+" x="-3" y="0">&#xe263;</text>,<text id="normal" x="-3.7" y="0">&#xe0a3;</text>,<text id="normal-" x="-3.7" y="0">&#xe0a3;</text>,<text id="normal+" x="-3.7" y="0">&#xe0a4;</text>,<g id="circle-x"><text x="-3" y="0">&#xe263;</text><circle r="4" class="stroke"></circle></g>,<g id="circle-x-"><text x="-3" y="0">&#xe263;</text><circle r="4" class="stroke"></circle></g>,<path id="triangle" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="stroke-width:1.4"></path>,<path id="triangle-" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="stroke-width:1.4"></path>,<path id="triangle+" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="fill:#000"></path>,<path id="square" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="square-" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="square+" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="fill:#000"></path>,<path id="diamond" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="diamond-" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="diamond+" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="fill:#000"></path>,</defs>\n%%endsvg'.split(","),
S='%%beginsvg\n,<style type="text/css">\n,.bf {font-family:sans-serif; font-size:7px}\n,</style>\n,<defs>\n,<rect id="clr" x="-3" y="-1" width="6" height="5" fill="white"></rect>\n,<rect id="clr2" x="-3" y="-1" width="11" height="5" fill="white"></rect>\n'.split(","),v;K.prototype.reset=function(){this.lline=this.attr="";this.rline="|";this.lnum=""};D.prototype.inc=function(a,b){this.counters[a][b]=(this.counters[a][b]||0)+1};D.prototype.clear=function(a){a=Object.keys(a);var b=y(a.length,0);this.counters=
{note:p(a,b),nopr:p(a,b),nopt:p(a,b)}};D.prototype.getv=function(a,b){return this.counters[a][b]};D.prototype.prcnt=function(a){for(var b in this.counters.note)0!=this.getv("nopr",b)&&u("part %d, voice %d has %d skipped non printable notes",[a,b,this.getv("nopr",b)]),0!=this.getv("nopt",b)&&u("part %d, voice %d has %d notes without pitch",[a,b,this.getv("nopt",b)]),0==this.getv("note",b)&&u("part %d, skipped empty voice %d",[a,b])};z.prototype.initVoices=function(a){this.vtimes={};this.voices={};
this.lyrics={};for(var b in this.vnums)this.vtimes[b]=0,this.voices[b]=[],this.lyrics[b]=[];a&&this.cnt.clear(this.vnums)};z.prototype.incTime=function(a){this.tijd+=a;0>this.tijd&&(this.tijd=0);this.tijd>this.maxtime&&(this.maxtime=this.tijd)};z.prototype.appendElemCv=function(a,b){for(var c in a)this.appendElem(c,b)};z.prototype.insertElem=function(a,b){var c=new C(b);c.tijd=0;this.voices[a].unshift(c)};z.prototype.appendObj=function(a,b,c){b.tijd=this.tijd;this.voices[a].push(b);this.incTime(c);
this.tijd>this.vtimes[a]&&(this.vtimes[a]=this.tijd)};z.prototype.appendElemT=function(a,b,c){b=new C(b);b.tijd=c;this.voices[a].push(b)};z.prototype.appendElem=function(a,b,c){this.appendObj(a,new C(b),0);c&&this.cnt.inc("note",a)};z.prototype.appendNote=function(a,b,c){b.ns.push(b.ntdec+c);this.appendObj(a,b,parseInt(b.dur));"z"!=c&&"x"!=c&&(this.lastnote=b,this.cnt.inc("note",a),b.grace||this.lyrics[a].push(b.lyrs))};z.prototype.getLastRec=function(a){return this.gMaten.length?(a=this.gMaten[this.gMaten.length-
1][a],a[a.length-1]):null};z.prototype.getLastMelis=function(a,b){if(this.gLyrics.length){var c=this.gLyrics[this.gLyrics.length-1][a];if(b in c)return c[b][1]}return 0};z.prototype.addChord=function(a,b){for(var c=0;c<a.before.length;c++){var d=a.before[c];0>this.lastnote.before.indexOf(d)&&this.lastnote.before.unshift(d)}this.lastnote.ns.push(a.ntdec+b)};z.prototype.addBar=function(a,b){b.mdur&&this.maxtime>b.mdur&&u("measure %d in part %d longer than metre",[b.ixm+1,b.ixp+1]);this.tijd=this.maxtime;
for(var c in this.vnums){if(b.lline||b.lnum){var d=this.getLastRec(c);if(d){var f=d.str;b.lline&&(f=(f+b.lline).replace(/:\|:/g,"::").replace(/\|\|/g,"|"));3==this.nvlt?b.ixp+parseInt(c)==Math.min.apply(null,F(this.vnums))&&(f+=b.lnum):4==this.nvlt?parseInt(c)==Math.min.apply(null,F(this.vnums))&&(f+=b.lnum):b.lnum&&(f+=b.lnum,this.repbra=1);d.str=f}else b.lline&&this.insertElem(c,"|:")}a&&(d=this.getLastRec(c))&&(d.str+=a);b.attr&&this.insertElem(c,""+b.attr);this.appendElem(c," "+b.rline);this.voices[c]=
Y(this.voices[c],b);for(var d=this.lyrics[c],f={},e=d.reduce(function(a,b){return a.concat(F(b))},[]),g=Math.max.apply(null,e.concat([0]));0<g;--g){var e=d.map(function(a){return a[g]||""}),h=this.getLastMelis(c,g);f[g]=T(e,h)}this.lyrics[c]=f;W(this.voices[c])}this.gMaten.push(this.voices);this.gLyrics.push(this.lyrics);this.tijd=this.maxtime=0;this.initVoices()};z.prototype.outVoices=function(a,b){var c,d,f,e,g,h,k,l,n;g={};k=Math.min.apply(null,F(this.vnums)||[1]);for(l in this.vnums)if(0!=this.cnt.getv("note",
l)){if(v.denL)h=v.denL;else{var m,r;h=l;n=this.gMaten;e=a;c=0;d=da;for(var q=[4,8,16];q.length;){var w=q.shift(),t=0;for(r=0;r<n.length;++r){var u=n[r][h];for(m=0;m<u.length;++m){var p=u[m];p instanceof C||0==p.dur||(t+=L(p,e,w).length)}}t<d&&(c=w,d=t)}h=c}v.cmpL.push(h);m=[];r={};for(n=0;n<this.gMaten.length;++n){e=this.gMaten[n][l];m.push(X(e,a,n,b,h));e=void 0;q=this.gLyrics;if(0!=n)for(e in c=this.gMaten[n][l],d=q[n][l],q=q[n-1][l],q)if(w=q[e][1],!(e in d)&&w){w=c;t=[];for(u=0;u<w.length;++u)if(p=
w[u],p instanceof B&&!p.grace){if("z"==p.ns[0]||"x"==p.ns[0])break;t.push("_")}(w=t.join(" "))&&(d[e]=[w,0])}c=this.gLyrics[n][l];for(f in c)if(e=c[f],e=e[0],f in r){for(;r[f].length<n;)r[f].push("");r[f].push(e)}else r[f]=y(n,"").concat([e])}for(f in r)e=r[f],h=m.length-e.length,r[f]=e.concat(y(h,""));v.add("V:"+this.vceCnt);this.repbra&&(1==this.nvlt&&1<this.vceCnt&&v.add("I:repbra 0"),2==this.nvlt&&parseInt(l)>k&&v.add("I:repbra 0"));0<this.cpl?this.bpl=0:0==this.bpl&&(this.cpl=100);for(h=0;m.length;){n=
1;for(e=m[0];n<m.length&&!(0<this.cpl&&e.length+m[n].length>=this.cpl)&&!(0<this.bpl&&n>=this.bpl);)e+=m[n],n+=1;h+=n;v.add(e+" %"+h);m.splice(0,n);c=J(r,1);for(d=0;d<c.length;++d)e=c[d],f=e[0],e=e[1],v.add("w: "+e.slice(0,n).join("|")+"|"),e.splice(0,n)}g[l]=this.vceCnt;this.vceCnt+=1}this.gMaten=[];this.gLyrics=[];this.cnt.prcnt(b+1);return g};E.prototype.add=function(a){this.outlist.push(a+"\n")};E.prototype.info=function(a,b){this.infolist.push(("undefined"==typeof b||b?"-- ":"")+a)};E.prototype.mkHeader=
function(a,b,c,d,f){var e=[],g=[],h,k,l,n,m,r,q;n=a.slice();for(q=0;q<b.length;++q){h=b[q];try{P(h,["",""],"",a,e,g)}catch(ea){u("lousy musicxml: error in part-list",[])}}b=g.join(" ");a={};for(q=0;q<n.length;++q)k=n[q],h=e[q],l=h[1],h=h[2],0!=k.length&&(k=k[0][0],l=l.replace(/\n/g,"\\n").replace(/\.:/g,".").replace(/^:|:$/g,""),h=h.replace(/\n/g,"\\n").replace(/\.:/g,".").replace(/^:|:$/g,""),a[k]=(l?'nm="'+l+'"':"")+(h?' snm="'+h+'"':""));e=[t("X:%d\n%s\n",[this.X,this.title])];""!==this.scale&&
e.push("%%scale "+this.scale+"\n");""!==this.pagewidth&&e.push("%%pagewidth "+this.pagewidth+"cm\n");""!==this.leftmargin&&e.push("%%leftmargin "+this.leftmargin+"cm\n");""!==this.rightmargin&&e.push("%%rightmargin "+this.rightmargin+"cm\n");b&&1<g.length&&e.push("%%score "+b+"\n");n=this.tempo?t("Q:%d/%d=%s\n",[this.tempo_units[0],this.tempo_units[1],this.tempo]):"";g=[];for(q=0;q<this.cmpL.length;++q)h=this.cmpL[q],g[h]=(g[h]||0)+1;g=J(g);g=g[g.length-1][0];g=this.denL?this.denL:g;e.push(t("L:1/%d\n%sM:%s\n",
[g,n,this.mtr]));e.push(t("I:linebreak $\nK:%s\n",[this.key]));this.stemless&&e.push("U:s=!stemless!\n");n=Object.keys(d).sort();for(q=0;q<n.length;++q)e=e.concat(d[n[q]]);this.dojef=0;for(r in this.clefs){h=c[r-1];q=h[0];b=h[1];l=h[2];k=h[3];n=h.slice(4);h=this.clefs[r];n.length&&0>h.indexOf("perc")&&(h=(h+" map=perc").trim());e.push(t("V:%d %s %s\n",[r,h,a[r]||""]));r in d&&(e.push(t("%%voicemap tab%d\n",[r])),e.push("K:none\nM:none\n%%clef none\n%%staffscale 1.6\n%%flatbeams true\n%%stemdir down\n"));
-1<h.indexOf("perc")&&e.push("K:none\n");1<this.volpan?(0<q&&q!=r&&e.push("%%MIDI channel "+q+"\n"),0<b&&e.push("%%MIDI program "+(b-1)+"\n"),0<=l&&e.push("%%MIDI control 7 "+l+"\n"),0<=k&&e.push("%%MIDI control 10 "+k+"\n")):0<this.volpan&&(n.length&&0<q&&e.push("%%MIDI channel "+q+"\n"),0<b&&e.push("%%MIDI program "+(b-1)+"\n"));for(q=0;q<n.length;++q)if(h=n[q].nt,l=n[q].step,b=n[q].midi,(k=n[q].nhd)||(k="normal"),M(h)!=b||h!=l)0<this.volpan&&e.push("%%MIDI drummap "+h+" "+b+"\n"),e.push("I:percmap "+
h+" "+l+" "+b+" "+k+"\n"),this.dojef=this.tstep;g!=this.cmpL[r-1]&&e.push("L:1/"+this.cmpL[r-1]+"\n")}this.outlist=e.concat(this.outlist);c=Object.keys(f).sort();if(c.length){m=[];var w=this.shiftStem?'<g id="kop%s" class="bf"><use xlink:href="#clr"></use><text x="-2" y="3">%s</text></g>\n'.replace("-2","-5"):'<g id="kop%s" class="bf"><use xlink:href="#clr"></use><text x="-2" y="3">%s</text></g>\n',p=this.shiftStem?'<g id="kop%s" class="bf"><use xlink:href="#clr2"></use><text x="-2" y="3">%s</text></g>\n'.replace("-2",
"-5"):'<g id="kop%s" class="bf"><use xlink:href="#clr2"></use><text x="-2" y="3">%s</text></g>\n';d=this.shiftStem?S.map(function(a){return a.replace("-3","-6")}):S;c.forEach(function(a){m.push(1<a.length?t(p,[a,a]):t(w,[a,a]))});this.outlist=d.concat(m,"</defs>\n%%endsvg\n",this.outlist)}};E.prototype.writeall=function(){var a=v.outlist.join("");this.dojef&&(a=ba(a));return[a,this.infolist.join("\n")]};x.prototype.matchSlur=function(a,b,c,d,f,e){if(-1!=["start","stop"].indexOf(a))if(b||(b="1"),b in
this.slurBuf){var g=this.slurBuf[b],h=g[0],k=g[1],l=g[2],g=g[3];a!=h?(c!=k||"start"!=h||g&&e||(l.before.unshift("("),d.after+=")"),delete this.slurBuf[b]):(u("double slur numbers %s-%s in part %d, measure %d, voice %d note %s, first discarded",[a,b,this.msr.ixp+1,this.msr.ixm+1,c,d.ns]),this.slurBuf[b]=[a,c,d,f])}else this.slurBuf[b]=[a,c,d,f]};x.prototype.doNotations=function(a,b,c){for(var d=Object.keys(Q).sort(),f=0;f<d.length;++f){var e=d[f],g=Q[e];b.find(e).length&&a.before.push(g)}f=b.find("ornaments>tremolo");
f.length&&(e=f.attr("type"),d="start"==e?"-":"","single"!=e&&(a.fact=null),"stop"!=e&&(f=m(parseInt(f.text()),"/"),a.before.unshift("!"+f+d+"!")));d=b.find("technical>fingering");c||d.each(function(){a.ntdec+="!"+$(this).text()+"!"});d=b.find("technical>string");d.length&&c&&(this.tstep?(c=b.find("technical>fret"),c.length&&(a.tab=[d.eq(0).text(),c.eq(0).text()])):d.each(function(){var b="!"+$(this).text()+"!";0>a.ntdec.indexOf(b)&&(a.ntdec+=b)}));c=b.find("ornaments>wavy-line");if(c.length)switch(c.attr("type")){case "start":a.before.unshift("!trill(!");
break;case "stop":a.before.unshift("!trill)!")}c=b.find("glissando");0==c.length&&(c=b.find("slide"));c.length&&(b="wavy"==c.attr("line-type")?"~":"-","start"==c.attr("type")?a.before.unshift(t("!%s(!",[b])):"stop"==c.attr("type")&&a.before.unshift(t("!%s)!",[b])))};x.prototype.tabnote=function(a,b,c,d,f){var e,g,h,k,l;k=this.step_map[b]+parseInt(a||"0");11<k&&(c+=1,k-=12);0>k&&(--c,k+=12);a=f.tab[0];b=f.tab[1];for(l=0;4>l;++l){e=this.note_alts[l%3][k];h=c;-1<["^B","^^B"].indexOf(e)&&--h;-1<["_C",
"__C"].indexOf(e)&&(h+=1);if(-1<e.indexOf("/")||3==l)h=9;e=I(e,h);g=this.tabmap[[d,e]]||["",""];h=g[0];g=g[1];if(!h)break;if(a==h)return e;3==l&&(u("rejected: voice %d note %s string %s fret %s remains: string %s fret %s",[d,e,a,b,h,g]),f.tab=[h,g])}this.tabmap[[d,e]]=f.tab;return e};x.prototype.ntAbc=function(a,b,c,d,f,e){var g={"double-flat":-2,"flat-flat":-2,flat:-1,natural:0,sharp:1,"sharp-sharp":2,"double-sharp":2};b+=this.clefOct[this.curStf[d]]||0;var h=c.find("accidental").text(),k=c.find("pitch>alter").text();
if(f.tab)return this.tabnote(k,a,b,d,f);e&&this.tstep&&(f=["__","_","","^","^^"][parseInt(k||"0")+2]+I(a,b),u("no string notation found for note %s in voice %d",[f,d]));b=I(a,b);!k&&this.msralts[a]&&(k=0);f=b+"#"+d;!k&&f in this.curalts&&(k=0);if(""===h&&""===k)return b;if(""!=h)k=g[h];else{k=parseFloat(k);if(f in this.curalts){if(k==this.curalts[f])return b}else if(k==(this.msralts[a]||0))return b;if(c.find("tie").add(c.find("notations>tied")).get().some(function(a){return"stop"==a.getAttribute("type")}))return b;
u("accidental %d added in part %d, measure %d, voice %d note %s",[k,this.msr.ixp+1,this.msr.ixm+1,d+1,b])}this.curalts[f]=k;return b=["__","_","=","^","^^"][k+2]+b};x.prototype.doNote=function(a){var b=new B(0,null),c=parseInt(a.find("voice").text()||"1");this.isSib&&(c+=100*(a.find("staff").text()||1));var d=0<a.find("chord").length,f=a.find("pitch>step").text()||a.find("unpitched>display-step").text(),e=a.find("pitch>octave").text()||a.find("unpitched>display-octave").text(),g=0<a.find("rest").length,
h=a.find("time-modification>actual-notes").text();if(h){var k=a.find("time-modification>normal-notes").text();b.fact=[parseInt(h),parseInt(k)]}b.tup=a.find("notations>tuplet").map(function(){return $(this).attr("type")}).get();k=a.find("duration").text();h=a.find("grace");b.grace=0<h.length;b.before=[""];b.after="";b.grace&&!this.ingrace&&(this.ingrace=1,b.before=["{"],"yes"==h.attr("slash")&&b.before.push("/"));if(h=!b.grace&&this.ingrace)this.ingrace=0,this.msc.lastnote.after+="}";if(!k||b.grace)k=
0;if(!g&&"no"==a.attr("print-object")){if(d)return;g=1}b.dur=parseInt(k);g||f&&e||(this.msc.cnt.inc("nopt",c),e=5,f="E");var k=0==(this.curClef&&this.curClef[this.curStf[c]]||"").indexOf("tab"),l=a.find("notations");l.length&&this.doNotations(b,l,k);l=a.find("stem");!g&&l.length&&"none"==l.text()&&(!k||c in this.hasStems||this.tstep)&&(b.before.push("s"),v.stemless=1);l=a.find("accidental");l.length&&"yes"==l.attr("parentheses")&&(b.ntdec+="!courtesy!");g=g?"no"==a.attr("print-object")||k?"x":"z":
this.ntAbc(f,parseInt(e),a,c,b,k);if(a.find("unpitched").length){k=this.curClef[this.curStf[c]];f=U(f,parseInt(e),k,this.tstep);e=a.find("instrument");e=e.length?e.attr("id"):"dummyId";e=this.drumInst[e]||M(g);k=a.find("notehead");l=k.text().replace(" ","-");"x"==l&&(g="^"+g.replace(/\^/g,"").replace(/_/g,""));if("circle-x"==l||"diamond"==l||"triangle"==l)g="_"+g.replace(/\^/g,"").replace(/_/g,"");"yes"==k.attr("filled")&&(l+="+");"no"==k.attr("filled")&&(l+="-");this.drumNotes[c+";"+g]=[f,e,l]}f=
a.find("tie").add(a.find("notations>tied")).get();f.some(function(a){return"start"==a.getAttribute("type")})&&(g+="-");f=a.find("beam").map(function(){return $(this).text()}).get();b.beam=-1<f.indexOf("continue")||-1<f.indexOf("end")||b.grace;f=a.find("lyric");for(e=k=0;e<f.length;++e){var l=$(f[e]),n=parseInt((l.attr("number")||"1").replace(/^.*verse/,""));0==n?n=k+1:k=n;b.lyrs[n]=aa(l)}d?this.msc.addChord(b,g):(d=parseInt(a.find("staff").text()||"1"),this.curStf[c]!=d&&(f=d-this.curStf[c],this.curStf[c]=
d,this.msc.appendElem(c,"[I:staff "+(0<f?"+":"")+f+"]")),this.msc.appendNote(c,b,g));f=a.find("notations>slur");for(e=0;e<f.length;++e)a=$(f[e]),this.matchSlur(a.attr("type"),a.attr("number"),c,this.msc.lastnote,b.grace,h)};x.prototype.doAttr=function(a){var b,c,d,f,e,g,h,k,l,n,m,r;b={C1:"alto1",C2:"alto2",C3:"alto",C4:"tenor",F4:"bass",F3:"bass3",G2:"treble",TAB:"tab",percussion:"perc"};if(c=a.find("divisions").text())this.msr.divs=parseInt(c);c=parseInt(a.find("transpose>chromatic").text()||"0");
d=a.find("key>fifths").first().text();f=0==this.msc.tijd&&0==this.msr.ixm;d&&(e=V(parseInt(d),a.find("key>mode").first().text()||"major"),d=e[0],this.msralts=e[1],f&&!c&&"none"==v.key?v.key=d:d==v.key&&f||(this.msr.attr+="[K:"+d+"]"));if(d=a.find("time>beats").text())e=a.find("time>beat-type").text(),g=d+"/"+e,f?v.mtr=g:this.msr.attr+="[M:"+g+"]",this.msr.mdur=this.msr.divs*parseInt(d)*4/parseInt(e);var q=this;a.find("measure-style").each(function(){var a,b,c,d,e,f,g;a=parseInt($(this).attr("number")||
"1");b=q.stfMap[a];$(this).find("measure-repeat").each(function(){c=$(this).attr("type");"start"==c?(q.repeat_str[a]=[q.msr.ixm,$(this).text()],b.forEach(function(b){q.msc.insertElem(b,q.repeat_str[a])})):"stop"==c&&(d=q.repeat_str[a][0],f=q.repeat_str[a][1],e=q.msr.ixm-d,f?(g=f+" ",e/=parseInt(f)):g="",q.repeat_str[a][0]=t("[I:repeat %s%d]",[g,e]))})});(d=a.find("transpose>octave-change").text()||"")&&(c+=12*parseInt(d));g=a.find("clef");for(e=0;e<g.length;e++){h=$(g[e]);d=parseInt(h.attr("number")||
"1");k=h.find("sign").text();l="percussion"!=k&&"TAB"!=k?h.find("line").text()||"":"";l=b[k+l]||"";h=h.find("clef-octave-change").text()||"0";l+={"-2":"-15","-1":"-8",1:"+8",2:"+15"}[h]||"";this.clefOct[d]=-parseInt(h);c&&(l+=" transpose="+c);n=a.find("staff-details");if(n.length&&(n.attr("number")||1)==d){if(h=n.find("staff-lines").text())k="3"==h&&"TAB"==k?"|||":h,l+=" stafflines="+k,this.stafflines=parseInt(h);var w=[];n.find("staff-tuning").each(function(){w.push($(this).find("tuning-step").text()+
$(this).find("tuning-octave").text())});w.length&&(l+=t(" strings=%s",[w.join(",")]));(k=n.find("capo").text())&&(l+=t(" capo=%s",[k]))}this.curClef[d]=l;if(f)this.clefMap[d]=l;else for(h=this.stfMap[d],r=0;r<h.length;++r)n=h[r],d!=this.curStf[n]&&(m=d-this.curStf[n],this.curStf[n]=d,k=0<m?"+":"",this.msc.appendElem(n,"[I:staff "+k+m+"]")),this.msc.appendElem(n,"[K:"+l+"]")}};x.prototype.findVoice=function(a,b){var c,d,f,e;f=b.eq(a);c=parseInt(f.find("staff").text()||"1");d=this.stfMap[c][0];if(this.dirtov1)return{sn:c,
v:d,v1:d};for(e=a;e<b.length;++e){f=b.eq(e);if("note"==f.prop("nodeName"))return c=parseInt(f.find("staff").text()||"1"),f=parseInt(f.find("voice").text()||"1"),this.isSib&&(f+=100*c),{sn:c,v:f,v1:d};if("backup"==f.prop("nodeName"))break}return{sn:c,v:d,v1:d}};x.prototype.doDirection=function(a,b,c){function d(a,b,c,d,e){b&&(c=0<=b.indexOf("!8v")?a.stfMap[e]:[c],c.forEach(function(c){null!=d?a.msc.appendElemT(c,b.replace("(",")").replace("ped","ped-up"),d):a.msc.appendElem(c,b)}))}function f(a,b,
c,e){var f,h,l;l={down:"!8va(!",up:"!8vb(!",crescendo:"!<(!",diminuendo:"!>(!",start:"!ped!"};k=g.attr("type")||"";f=b+(g.attr("number")||"1");if(k in l)l=l[k],f in a.dirStk?(h=a.dirStk[f],delete a.dirStk[f],"stop"==h.type?d(a,l,c,h.tijd,e):(u("%s direction %s has no stop in part %d, measure %d, voice %d",[b,h.type,a.msr.ixp+1,a.msr.ixm+1,c+1]),a.dirStk[f]={type:k,vs:c})):a.dirStk[f]={type:k,vs:c};else if("stop"==k)f in a.dirStk?(h=a.dirStk[f],delete a.dirStk[f],k=h.type,c=h.vs,"stop"==k?(u("%s direction %s has double stop in part %d, measure %d, voice %d",
[b,k,a.msr.ixp+1,a.msr.ixm+1,c+1]),l=""):l=l[h.type].replace("(",")").replace("ped","ped-up")):(a.dirStk[f]={type:"stop",tijd:a.msc.tijd},l="");else throw"wrong direction type";d(a,l,c,null,e)}var e,g,h,k,l,n,m,r,q,w,p,y="",x;e=a.attr("placement");l=this.findVoice(b,c);c=l.sn;b=l.v;l=l.v1;var z="",A={dacapo:"D.C.",dalsegno:"D.S.",tocoda:"dacoda",fine:"fine",coda:"O",segno:"S"};g=a.find("sound");if(g.length){r=g.find("midi-instrument");if(r.length){h=g.find("midi-instrument>midi-program").text();q=
g.find("midi-instrument>midi-channel").text();for(w in this.vceInst)this.vceInst[w]==r.attr("id")&&(b=w);(w=(h?h-1:q)+"")&&0<v.volpan&&this.msc.appendElem(b,"[I:MIDI= "+(h?"program":"channel")+" "+w+"]")}if(h=g.attr("tempo"))h=parseFloat(h).toFixed(0),x=[1,4];for(p in A)if(g.attr(p)){z=A[p];break}}a=a.children("direction-type");if(a.length){p={whole:[1,1],half:[1,2],quarter:[1,4],eighth:[1,8]};w=a.find("metronome");w.length&&(g=w.find("beat-unit").text()||"",x=g in p?p[g]:p.quarter,w.find("beat-unit-dot").length&&
(x=G(3*x[0],2*x[1])),h=w.find("per-minute").text());g=a.find("wedge");g.length&&f(this,"wedge",b);p=a.find("words");0==p.length&&(p=a.find("rehearsal"));for(w=0;w<p.length;++w){if(z){this.msc.appendElem(b,t("!%s!",[z]),1);break}n="below"==e?"_":"^";A=$(p[w]);0>parseFloat(A.attr("default-y")||"0")&&(n="_");y+=A.text().replace(/"/g,'\\"').replace(/\n/g,"\\n")}y=y.trim();for(m in R)e=R[m],a.find("dynamics>"+m).length&&this.msc.appendElem(b,e,1);a.find("coda").length&&this.msc.appendElem(b,"O",1);a.find("segno").length&&
this.msc.appendElem(b,"S",1);g=a.find("octave-shift");g.length&&f(this,"octave-shift",b,c);g=a.find("pedal");g.length&&this.ped&&(this.pedVce||(this.pedVce=b),f(this,"pedal",this.pedVce));"diatonic fretting"==a.find("other-direction").text()&&(this.diafret=1)}h&&(h=parseFloat(h).toFixed(0),0==this.msc.tijd&&0==this.msr.ixm?(v.tempo=h,v.tempo_units=x):this.msc.appendElem(l,t("[Q:%d/%d=%s]",[x[0],x[1],h])));y&&this.msc.appendElem(b,'"'+n+y+'"',1)};x.prototype.doHarmony=function(a,b,c){var d,f,e,g,h,
k,l;c=this.findVoice(b,c).v;d={major:"",minor:"m",augmented:"+",diminished:"dim",dominant:"7","half-diminished":"m7b5"};b={major:"maj",dominant:"",minor:"m",diminished:"dim",augmented:"+",suspended:"sus"};f={second:"2",fourth:"4",seventh:"7",sixth:"6",ninth:"9","11th":"11","13th":"13"};e={1:"#",0:"","-1":"b"};g=a.find("root>root-step","").text();h=e[a.find("root>root-alter").text()]||"";k="";l=a.find("kind").text();l in d?l=d[l]:-1<l.indexOf("-")?(d=l.split("-"),l=d[0],d=d[1],l=(b[l]||"")+(f[d]||
""),0==l.indexOf("sus")&&(k=l,l="")):"none"==l&&(l=a.find("kind").attr("text"));f=a.find("degree");for(b=0;b<f.length;++b)d=$(f[b]),l+=(e[d.find("degree-alter").text()]||"")+d.find("degree-value").text();l=l.replace("79","9").replace("713","13").replace("maj6","6");a=a.find("bass>bass-step").text()+(e[a.find("bass>bass-alter").text()]||"");this.msc.appendElem(c,'"'+g+h+l+k+(a&&"/"+a)+'"',1)};x.prototype.doBarline=function(a){var b=a.find("repeat"),c=0;b.length&&(c=b.attr("direction"));if(this.unfold)return c?
"forward"==c?1:2:0;"right"==(a.attr("location")||"right")&&(b=a.find("bar-style").text(),"light-light"==b?this.msr.rline="||":"light-heavy"==b&&(this.msr.rline="|]"));c&&("forward"==c?this.msr.lline=":":this.msr.rline=":|");a=a.find("ending");a.length&&("start"==a.attr("type")?(a=(a.attr("number")||"1").replace(/\./g,"").replace(/ /g,""),/^[\d,]+$/.test(a)||(a='"'+a.trim()+'"'),this.msr.lnum=a):"|"==this.msr.rline&&(this.msr.rline="||"));return 0};x.prototype.doPrint=function(a){if("yes"==a.attr("new-system")||
"yes"==a.attr("new-page"))return this.nolbrk?"":"$"};x.prototype.doPartList=function(a){var b,c,d,f,e,g,h,k,l,m;f=a.find("part-list>score-part");for(b=0;b<f.length;++b){c=f[b];e={};g=$(c).find("midi-instrument");for(c=0;c<g.length;++c){h=$(g[c]);l=["midi-channel","midi-program","volume","pan"];k=[];for(d=0;d<l.length;++d)m=l[d],k.push(h.find(m).text()||this.midDflt[d]);d=1*k[3];-90<=d&&90>=d&&(d=(d+90)/180*127);e[h.attr("id")]=[parseInt(k[0]),parseInt(k[1]),1.27*parseFloat(k[2]),d];(k=h.find("midi-unpitched").text())&&
(this.drumInst[h.attr("id")]=k-1)}this.instMid.push(e)}a=a.find("part-list");k=Z(a);return H(k,{},[])[0]};x.prototype.mkTitle=function(a){var b,c,d=[],f=[],e=[],g,h,k,l,m;b=a.find("work>work-title").text().trim();c=a.find("movement-title").text().trim();g=a.find("identification>creator");for(h=0;h<g.length;++h)k=$(g[h]),l=k.text(),k=k.attr("type"),l&&(l=l.split("\n").map(function(a){return a.trim()}),"composer"==k?d.push.apply(d,l):"lyricist"!=k&&"transcriber"!=k||f.push.apply(f,l));g=a.find("identification>rights");
for(h=0;h<g.length;++h)if(l=$(g[h]).text())l=l.split("\n").map(function(a){return a.trim()}),f.push.apply(f,l);g=a.find("credit");for(h=0;h<g.length;++h){l="";k=$(g[h]).find("credit-words");for(m=0;m<k.length;++m)l+=$(k[m]).text();e.push(l.replace(/\s*[\r\n]\s*/g," "))}e=function(a){function g(a){return a&&-1<k.indexOf(a)}var h=[],k,l;for(l=0;l<e.length;++l)k=e[l],6>a&&(k&&-1<b.indexOf(k)||k&&-1<c.indexOf(k))||5>a&&(k&&-1<d.indexOf(k)||k&&-1<f.indexOf(k))||4>a&&(b&&-1<k.indexOf(b)||c&&-1<k.indexOf(c))||
3>a&&(d.some(g)||f.some(g))||2>a&&/^[\d\W]*$/.test(k)||h.push(k);0==a&&b+c&&(h="");return h}(this.ctf);b&&(b="T:"+b.replace(/\n/g,"\nT:")+"\n");c&&(b+="T:"+c.replace(/\n/g,"\nT:")+"\n");e.length&&(b+=e.map(function(a){return"T:"+a}).join("\n")+"\n");d.length&&(b+=d.map(function(a){return"C:"+a}).join("\n")+"\n");f.length&&(b+=f.map(function(a){return"Z:"+a}).join("\n")+"\n");b&&(v.title=b.substr(0,b.length-1));(this.isSib=0<=a.find("identification>encoding>software").text().indexOf("Sibelius"))&&
u("Sibelius MusicXMl is unreliable",[])};x.prototype.doDefaults=function(a){var b,c,d,f;this.doPageFmt&&(b=a.find("defaults"),b.length&&(a=b.find("scaling>millimeters").text(),c=b.find("scaling>tenths").text(),c=a/c/10,a=b.find("page-layout>page-width").text()*c,d=b.find("page-layout>page-margins").first(),b=d.find("left-margin").text(),d=d.find("right-margin").text(),f=10*c/.2117,!v.scale&&f&&(v.scale=f.toFixed(2)),!v.pagewidth&&a&&(v.pagewidth=a.toFixed(2)),v.leftmargin||""==b||(v.leftmargin=(b*
c).toFixed(2)),v.rightmargin||""==d||(v.rightmargin=(d*c).toFixed(2))))};x.prototype.locStaffMap=function(a,b){var c={};this.vceInst={};this.msc.vnums={};this.hasStems={};for(var d=a.find("measure>note"),f=0;f<d.length;f++){var e=$(d[f]),g=parseInt(e.find("voice").text()||"1");this.isSib&&(g+=100*(e.find("staff").text()||1));this.msc.vnums[g]=1;var h=parseInt(e.find("staff").text()||"1");if(g in c){var k=c[g];k[h]=(k[h]||0)+1}else k={},k[h]=1,c[g]=k;k=e.find("instrument");k.length&&(this.vceInst[g]=
$(k).attr("id"));k=e.find("stem");0!=e.find("rest").length||0!=k.length&&"none"==k.text()||(this.hasStems[g]=1)}this.stfMap={};this.clefMap={};for(g in c){d=[];f=c[g];for(h in f)d.push([f[h],h]);d.sort(function(a,b){return b[0]-a[0]});d=d[0][1];this.stfMap[d]=(this.stfMap[d]||[]).concat([g]);this.curStf[g]=d}};x.prototype.addStaffMap=function(a){var b,c,d,f,e,g,h,k=[],l=Object.keys(this.stfMap).sort();for(c=0;c<l.length;++c){e=l[c];f=this.stfMap[e];g=[];h=[];for(b=0;b<f.length;++b)d=f[b],d in a&&
(g.push(a[d]),h.push(void 0==this.hasStems[d]));if(g.length)for(k.push(g),f=(e in this.clefMap)?this.clefMap[e]:"treble",b=0;b<g.length;++b)d=g[b],e="",0==f.indexOf("tab")&&(h[b]&&0>f.indexOf("nostems")&&(e=" nostems"),this.diafret&&0>f.indexOf("diafret")&&(e+=" diafret")),v.clefs[d]=f+e}this.gStfMap.push(k)};x.prototype.addMidiMap=function(a,b){var c=this.instMid[a],d,f=Object.keys(c);d=f.length?c[f[0]]:this.midDflt;var e=[],g,h,k,l=this;for(g in b)f=Object.keys(this.drumNotes).sort().filter(function(a){return a.split(";")[0]==
g}),k=f.map(function(a){return{nt:a.split(";")[1],step:l.drumNotes[a][0],midi:l.drumNotes[a][1],nhd:l.drumNotes[a][2]}}),h=b[g],f=this.vceInst[g]||"",f in c?e.push([h,c[f].concat(k)]):e.push([h,d.concat(k)]);e.sort(function(a,b){return a[0]-b[0]});e.forEach(function(a){l.midiMap.push(a[1])});d="E G B d f a c' e'".split(" ");for(var m,p,r="0 1- 1 1+ 2 3 3 4 4 5 6 6+ 7 8- 8 8+ 9 10 10 11 11 12 13 13+ 14".split(" "),f=Object.keys(this.tabmap).sort(),c=0;c<f.length;++c)h=f[c],e=h.match(/(\d+),(.*)/),
g=e[1],p=e[2],k=this.tabmap[h][0],m=this.tabmap[h][1],this.diafret&&(m=r[parseInt(m)]),h=b[g],k=this.stafflines-parseInt(k),e=this.tabVceMap[h]||[],e.push(t("%%map tab%d %s print=%s heads=kop%s\n",[h,p,d[k],m])),this.tabVceMap[h]=e,this.koppen[m]=1};x.prototype.parse=function(a){var b={},c=$(a);this.mkTitle(c);this.doDefaults(c);a=this.doPartList(c);for(var d=c.find("part"),f=0;f<d.length;++f){var e=d.eq(f),g=e.find("measure");this.locStaffMap(e,g);this.drumNotes={};this.clefOct={};this.curClef={};
this.tabmap={};this.diafret=0;this.stafflines=5;this.msc.initVoices(1);var h=e=0;for(this.msr=new K(f);this.msr.ixm<g.length;){var k=g.eq(this.msr.ixm),l=0,m="";this.msr.reset();this.curalts={};for(var p=k.children(),r=0;r<p.length;r++)switch(c=p.eq(r),c[0].nodeName){case "note":this.doNote(c);break;case "attributes":this.doAttr(c);break;case "direction":this.doDirection(c,r,p);break;case "sound":this.doDirection(k,r,p);break;case "harmony":this.doHarmony(c,r,p);break;case "barline":l=this.doBarline(c);
break;case "backup":c=parseInt(c.find("duration").text());this.msc.incTime(-c);break;case "forward":c=parseInt(c.find("duration").text());this.msc.incTime(c);break;case "print":m=this.doPrint(c)}this.msc.addBar(m,this.msr);1==l?(h=this.msr.ixm,this.msr.ixm+=1):2==l?1>e?(this.msr.ixm=h,e+=1):(e=0,this.msr.ixm+=1):this.msr.ixm+=1}g=this.msc.outVoices(this.msr.divs,f);this.addStaffMap(g);this.addMidiMap(f,g);for(var q in g)b[q]=g[q]}Object.keys(b).length?v.mkHeader(this.gStfMap,a,this.midiMap,this.tabVceMap,
this.koppen):u("nothing written, %s has no notes ...",[v.fnmext])};vertaal=function(a,b){var c={u:0,b:0,n:0,c:0,v:0,d:0,m:0,x:0,t:0,v1:0,noped:0,p:"f",s:0},d;for(d in b)c[d]=b[d];c.p=c.p?c.p.split(","):[];v=new E(".abc","",0,c);c=new x(c);try{c.parse(a)}catch(f){u("** exception occurred: %s",[f])}return v.writeall()}})();
